---
apiVersion: v1
kind: Pod
metadata:
  name: warp-client
  namespace: noobaa-benchmark
  labels:
    app: warp-client
spec:
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: warp
      image: minio/warp:latest
      imagePullPolicy: Always
      args:
        - client
        - 0.0.0.0:7761
      ports:
        - name: warp
          containerPort: 7761
          protocol: TCP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: "2"
          memory: 2Gi
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
