apiVersion: v1
kind: Service
metadata:
  name: warp-client
  namespace: noobaa-benchmark
spec:
  selector:
    app: warp-client
  ports:
    - name: warp
      protocol: TCP
      port: 7761
      targetPort: 7761
